codecov:
  notify:
    require_ci_to_pass: no

ignore:
  - "import/iomgr/**"
  - "src/tests/**"
  - "src/to_move_out/**"
  - "**/test_.*"
  - "**/*_test.c*"
  - "**/*_generated.h"
  - "**/*.pb.cc"
  - "**/*.pb.h"
  - "**/tests/*"
