# ##########   #######   ############
FROM ecr.vip.ebayc3.com/sds/sds_develop:2.1
LABEL description="Automated HomeStore compilation"

ARG CONAN_CHANNEL
ARG CONAN_USER
ARG BUILD_TYPE
ENV CONAN_USER=${CONAN_USER:-sds}
ENV CONAN_CHANNEL=${CONAN_CHANNEL:-develop}
ENV SOURCE_PATH=/tmp/source/
ENV BUILD_TYPE=${BUILD_TYPE:-default}

COPY conanfile.py ${SOURCE_PATH}
COPY cmake/ ${SOURCE_PATH}cmake
COPY CMakeLists.txt ${SOURCE_PATH}
COPY src/ ${SOURCE_PATH}src
COPY src/volume/homestore /usr/local/bin

WORKDIR /output
RUN conan install -pr ${BUILD_TYPE} --build missing ${SOURCE_PATH}

# Build the variants we will publish
ENV ASAN_OPTIONS=detect_leaks=0
RUN conan create -pr ${BUILD_TYPE} ${SOURCE_PATH} "${CONAN_USER}"/"${CONAN_CHANNEL}"

RUN find /root/.conan/data/homestore -name "obj_allocator_benchmark" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "perf_cache" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "perf_test_volume" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_avector" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_bitset" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_bitword" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_blkalloc" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_btree_crud" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_cache" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_composite_allocator" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_hash" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_iomgr_exec" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_load" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_mapping" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_obj_allocator" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_threadpool" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "test_volume" -exec mv {} /usr/local/bin \;
RUN find /root/.conan/data/homestore -name "vol_test.py" -exec mv {} /usr/local/bin \;

EXPOSE 5000

# ##########   #######   ############
