pipeline {
    agent { label 'sds-builder-2204' }

    environment {
        ORG = 'sds'
        HUB_URL = 'hub.tess.io'
        ARTIFACTORY_PASS = credentials('ARTIFACTORY_PASS')
        CONAN_USER = 'oss'
        STABLE_BRANCH = 'stable/v*'
    }

    stages {
        stage('Get Version') {
            steps {
                script {
                    PROJECT = sh(script: "grep -m 1 'name =' conanfile.py | awk '{print \$3}' | tr -d '\n' | tr -d '\"'", returnStdout: true)
                    VER = sh(script: "grep -m 1 'version =' conanfile.py | awk '{print \$3}' | tr -d '\n' | tr -d '\"'", returnStdout: true)
                    CONAN_CHANNEL = sh(script: "echo ${BRANCH_NAME} | sed -E 's,(\\w+-?\\d*)/.*,\\1,' | sed -E 's,-,_,' | tr -d '\n'", returnStdout: true)
                    SANITIZED_BRANCH = sh(script: "echo ${BRANCH_NAME} | sed -E 's,(\\w+-?\\d*)/.*,\\1,' | sed -E 's,-,_,' | tr -d '\n'", returnStdout: true)
                    HUB_PATH = "${HUB_URL}/${ORG}/${PROJECT}"
                    slackSend color: '#0063D1', channel: '#sds-ci', message: "*${PROJECT}/${SANITIZED_BRANCH}* is building."
                }
            }
        }

        stage('Build') {
            failFast true
            matrix {
                agent { label 'sds-builder-2204' }
                axes {
                    axis {
                        name 'BUILD_TYPE'
                        values 'release', 'debug'
                    }
                }

                stages {
                    stage("Refresh Locks") {
                        when { not {
                            branch "${STABLE_BRANCH}"
                        } }
                        steps {
                            script {
                                sh "./update_locks.sh"
                            }
                        }
                    }

                    stage("Build") {
                        steps {
                            script {
                                sh "conan create --lockfile locks/${BUILD_TYPE}_deps.lock ."
                                sh "find ${CONAN_USER_HOME} -type f -wholename '*bin/test_load' -exec cp {} .jenkins/test_load \\;"
                                sh "find ${CONAN_USER_HOME} -type f -wholename '*bin/test_volume' -exec cp {} .jenkins/test_volume \\;"
                                sh "find ${CONAN_USER_HOME} -type f -wholename '*bin/check_btree' -exec cp {} .jenkins/check_btree \\;"
                                sh "find ${CONAN_USER_HOME} -type f -wholename '*bin/test_log_store' -exec cp {} .jenkins/test_log_store \\;"
                                sh "find ${CONAN_USER_HOME} -type f -wholename '*bin/test_meta_blk_mgr' -exec cp {} .jenkins/test_meta_blk_mgr \\;"
                                sh "find ${CONAN_USER_HOME} -type f -wholename '*bin/hs_svc_tool ' -exec cp {} .jenkins/hs_svc_tool \\;"
                                sh "find . -type f -wholename '*test_scripts/vol_test.py' -exec cp -a {} .jenkins/vol_test.py \\;"
                                sh "find ${CONAN_USER_HOME} -type d -wholename '*bin/scripts' -exec cp -a {} .jenkins/scripts \\;"
                                sh "find ${CONAN_USER_HOME} -type f -wholename '*bin/test_log_store' -exec cp {} .jenkins/test_log_store \\;"
                                withDockerRegistry([credentialsId: 'sds-sds', url: "https://${HUB_URL}"]) {
                                    sh "docker build -t ${HUB_PATH}:${CONAN_CHANNEL}-${BUILD_TYPE} .jenkins/"
                                }
                            }
                        }
                    }

                   stage("Deploy Package") {
                            branch "${STABLE_BRANCH}"
                            expression { "${BUILD_TYPE}" != 'coverage' }
                            expression { "${BUILD_TYPE}" != 'sanitize' }
                        } }
                        steps {
                            sh "conan user -r ebay-local -p ${ARTIFACTORY_PASS} _service_sds"
                            sh "conan upload ${PROJECT}/${VER}@ -c --all -r ebay-local"
                        }
                    }
                    stage("Image") {
                        when { branch "${STABLE_BRANCH}" }
                        steps {
                            withDockerRegistry([credentialsId: 'sds-sds', url: "https://${HUB_URL}"]) {
                                sh "docker push ${HUB_PATH}:${CONAN_CHANNEL}-${BUILD_TYPE}"
                            }
                        }
                        post {
                            success {
                                slackSend color: '#85B717', channel: '#sds-ci', message: "*${HUB_PATH}:${SANITIZED_BRANCH}-${BUILD_TYPE}* has been uploaded to ECR."
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        failure {
            slackSend color: '#E43237', channel: '#${PROJECT}-build', message: "@here ${PROJECT} build *${PROJECT}/${SANITIZED_BRANCH}* has had a failure : ${BUILD_URL}"
        }
        success {
            slackSend color: '#85B717', channel: '#sds-ci', message: "*${PROJECT}/${SANITIZED_BRANCH}* has completed successfully."
        }
    }
}
