pipeline {
    agent any

    environment {
        ORG = 'sds'
        ARTIFACTORY_PASS = credentials('ARTIFACTORY_PASS')
        HOMESTORE_BUILD_TAG = "${GIT_COMMIT}"
        CONAN_USER = 'sds'
        MASTER_BRANCH = 'master'
        TESTING_BRANCH = 'testing/v*'
        STABLE_BRANCH = 'stable/v*'
    }

    stages {
        stage('Adjust Tag for Master/PR') {
            when { not { anyOf {
                branch "${TESTING_BRANCH}"
                branch "${STABLE_BRANCH}"
            } } }
            steps {
                script {
                    sh(script: "sed -Ei 's,version = .*\"([[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+).*,version = \"\\1-${env.BUILD_NUMBER}\",' conanfile.py")
                    BUILD_MISSING = "--build cascade --build missing"
                }
            }
        }
        stage('Adjust for Testing/Stable') {
            when { anyOf {
                branch "${TESTING_BRANCH}"
                branch "${STABLE_BRANCH}"
            } }
            steps {
                script {
                    BUILD_MISSING = ""
                }
            }
        }

        stage('Get Version') {
            steps {
                script {
                    PROJECT = sh(script: "grep -m 1 'name =' conanfile.py | awk '{print \$3}' | tr -d '\n' | tr -d '\"'", returnStdout: true)
                    VER = sh(script: "grep -m 1 'version =' conanfile.py | awk '{print \$3}' | tr -d '\n' | tr -d '\"'", returnStdout: true)
                    CONAN_CHANNEL = sh(script: "echo ${BRANCH_NAME} | sed -E 's,(\\w+-?\\d*)/.*,\\1,' | sed -E 's,-,_,' | tr -d '\n'", returnStdout: true)
                    ECR_PATH = "ecr.vip.ebayc3.com/${ORG}/${PROJECT}"
                    TAG = "${VER}@${CONAN_USER}/${CONAN_CHANNEL}"
                    slackSend color: '#0063D1', channel: '#sds-ci', message: "*${PROJECT}/${TAG}@${CONAN_USER}/${CONAN_CHANNEL}* is building."
                }
            }
        }

        stage('Tag Stable Build') {
            when { branch "${STABLE_BRANCH}" }
            steps {
                script {
                    TAG = "${VER}@"
                }
            }
        }

        stage('Build') {
            failFast true
            matrix {
                agent { label 'sds-builder' }
                axes {
                    axis {
                        name 'BUILD_TYPE'
                        values 'debug', 'release', 'test'
                    }
                    axis {
                        name 'SANITIZE'
                        values 'False', 'True'
                    }
                }
                excludes {
                    exclude {
                        axis {
                            name 'SANITIZE'
                            values 'True'
                        }
                        axis {
                            name 'BUILD_TYPE'
                            values 'release', 'test'
                        }
                    }
                }

                stages {
                    stage('Adjust Tag for Master/PR') {
                        when { not { anyOf {
                            branch "${TESTING_BRANCH}"
                            branch "${STABLE_BRANCH}"
                        } } }
                        steps {
                            sh(script: "sed -Ei 's,version = .*\"([[:digit:]]+\\.[[:digit:]]+\\.[[:digit:]]+).*,version = \"\\1-${env.BUILD_NUMBER}\",' conanfile.py")
                        }
                    }
                    stage("Build") {
                        steps {
                            sh "conan create ${BUILD_MISSING} -o homestore:sanitize=${SANITIZE} -pr ${BUILD_TYPE} . ${PROJECT}/${TAG}@${CONAN_USER}/${CONAN_CHANNEL}"
                        }
                        post {
                            failure {
                                archiveArtifacts artifacts: "/root/.conan/data/${PROJECT}/${TAG}/${CONAN_USER}/${CONAN_PASS}/build/*/src/logs/*", fingerprint: true
                            }
                        }
                    }
                    stage("Deploy") {
                        when {
                            expression { not { branch "PR_*" } }
                        }
                        steps {
                            sh "conan user -r ebay-local -p ${ARTIFACTORY_PASS} _service_sds"
                            sh "conan upload ${PROJECT}/${TAG}@${CONAN_USER}/${CONAN_CHANNEL} -c --all -r ebay-local"
                        }
                    }
                }
            }
        }

        stage('TestImage') {
            when {
                anyOf {
                    branch "develop"
                    branch "master"
                }
            }
            matrix {
                agent {
                    label 'sds-builder'
                }
                axes {
                    axis {
                        name 'BUILD_TYPE'
                        values 'debug', 'release', 'sanitize'
                    }
                }
                stages {
                    stage('Build') {
                        steps {
                            withDockerRegistry([credentialsId: 'sds-sds', url: "https://ecr.vip.ebayc3.com"]) {
                                sh "docker build --build-arg BUILD_TYPE=${BUILD_TYPE} --build-arg PKG_NAME=${PROJECT}/${TAG}@${CONAN_USER}/${CONAN_CHANNEL} -t ${ECR_PATH}:${CONAN_CHANNEL}-${BUILD_TYPE} .jenkins"
                                sh "docker push ${ECR_PATH}:${CONAN_CHANNEL}-${BUILD_TYPE}"
                                slackSend channel: '#sds-ci', message: "*${PROJECT}:${CONAN_CHANNEL}-${BUILD_TYPE}* has been pushed to ECR."
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        failure {
            slackSend color: '#E43237', channel: '#sds-ci', message: "*${PROJECT}/${TAG}@${CONAN_USER}/${CONAN_CHANNEL}* has had a failure : ${BUILD_URL}"
        }
        success {
            slackSend color: '#85B717', channel: '#sds-ci', message: "*${PROJECT}/${TAG}@${CONAN_USER}/${CONAN_CHANNEL}* has been uploaded to conan repo."
        }
    }
}
