#!/usr/bin/env bash
# Startup script for Homestore

container="homestore"
image="ecr.vip.ebayc3.com/sds/homestore:develop-test"

name_plus_date="${container}"-$(date +"%Y%m%d%H%M")
mount_base_dir=/opt/sds/mount
mount_src="${mount_base_dir}/${name_plus_date}"
mount_dst="/home/${container}"
mount_opts="--mount src=${mount_src},target=${mount_dst},type=bind"
host=$(hostname -f)
port=5000

entrypoint="cp /usr/local/bin/test_volume ${mount_dst}; \
            cp /usr/local/bin/test_mapping ${mount_dst}; \
            tail -f /dev/null"

start() {
    mkdir ${mount_src}
    docker pull ${image}
    docker run --rm --privileged ${mount_opts} -v ${mount_base_dir}:/tmp/source \
        --pid=host -e TZ=GMT+7 -d --name ${container} \
        --entrypoint /bin/sh ${image} -c "${entrypoint}"
}

stop() {
    docker stop ${container}
    docker rmi -f ${image}
}

status() {
    docker ps | grep ${container}
}

logs() {
    docker logs -t ${container}
}

login() {
    docker exec -it ${container} bash
}

test_normal() {
    docker exec -it ${container} bash -c \
        "cd /usr/local/bin; python vol_test.py --test_suits=normal"
}

test_recovery() {
    docker exec -it ${container} bash -c \
        "cd /usr/local/bin; python vol_test.py --test_suits=recovery"
}

test_vol_del() {
    docker exec -it ${container} bash -c \
        "cd /usr/local/bin; python vol_test.py --test_suits=vol_del"
}

test_sequence() {
    docker exec -it ${container} bash -c \
        "cd /usr/local/bin; python vol_test.py --test_suits=sequence"
}

case "$1" in
    'start')
            start
            ;;
    'stop')
            stop
            ;;
    'restart')
            stop
            sleep 5s
            start
            ;;
    'logs')
            logs
            ;;
    'login')
            login
            ;;
    'status')
            status
            ;;
    'test-normal')
            test_normal
            ;;
    'test-recovery')
            test_recovery
            ;;
    'test-vol-del')
            test_vol_del
            ;;
    'test-sequence')
            test_sequence
            ;;
    *)
            echo
            echo "Usage: $0 { start | stop | restart | logs | login | status | test-normal | test-recovery | test-vol-del | test-sequence }"
            echo
            exit 1
            ;;
esac

