#!/usr/bin/env bash
# Startup script for Homestore

container="homestore"
image="ecr.vip.ebayc3.com/sds/homestore:develop-test"

name_plus_date="${container}"-$(date +"%Y%m%d%H%M")
mount_base_dir=$(pwd)
mount_src="${mount_base_dir}/${name_plus_date}"
mount_dst="/home/${container}"
mount_opts="--mount src=${mount_src},target=${mount_dst},type=bind"
host=$(hostname -f)
port=5000

entrypoint="tail -f /dev/null"

start() {
    mkdir ${mount_src}
    docker pull ${image}
    docker run --rm --privileged ${mount_opts} -v ${mount_base_dir}:/tmp/source \
        --pid=host -e TZ=GMT-7 -d --name ${container} \
        --entrypoint /bin/sh ${image} -c "${entrypoint}"
}

stop() {
    docker stop ${container}
    docker rmi -f ${image}
}

status() {
    docker ps | grep ${container}
}

logs() {
    docker logs ${container}
}

login() {
    docker exec -it ${container} bash
}

test_normal() {
    docker exec -it ${container} bash -c \
        "cd /usr/local/bin; python vol_test.py --test_suits=normal >> ${mount_dst}/log_normal.txt"
}

test_recovery() {
    docker exec -it ${container} bash -c \
        "cd /usr/local/bin; python vol_test.py --test_suits=recovery >> ${mount_dst}/log_recovery.txt"
}

test_vol_del() {
    docker exec -it ${container} bash -c \
        "cd /usr/local/bin; python vol_test.py --test_suits=vol_del >> ${mount_dst}/log_vol_del.txt"
}

case "$1" in
    'start')
            start
            ;;
    'stop')
            stop
            ;;
    'restart')
            stop
            start
            ;;
    'logs')
            logs
            ;;
    'login')
            login
            ;;
    'status')
            status
            ;;
    'test_normal')
            test_normal
            ;;
    'test_recovery')
            test_recovery
            ;;
    'test_vol_del')
            test_vol_del
            ;;
    'test_all')
            test_normal
            test_recovery
            test_vol_del
            ;;
    *)
            echo
            echo "Usage: $0 { start | stop | restart | logs | login | status | test_normal | test_recovery | test_vol_del | test_all }"
            echo
            exit 1
            ;;
esac

