macro(can_build_io_tests ret)
    set(${ret} false)
    if (("${CONAN_TEST_TARGET}" STREQUAL "full") OR ("${CONAN_TEST_TARGET}" STREQUAL "spdk_mode") OR 
        ("${CONAN_TEST_TARGET}" STREQUAL "epoll_mode") OR ("${CONAN_TEST_TARGET}" STREQUAL "coverage"))
        set(${ret} true)
    endif()
endmacro()

macro(can_build_nonio_tests ret)
    set(${ret} false)
    can_build_io_tests(build_io_tests)
    if (${build_io_tests} OR ("${CONAN_TEST_TARGET}" STREQUAL "min"))
        set(${ret} true)
    endif()
endmacro()

macro(is_non_coverage_build ret)
    set(${ret} false)
    can_build_nonio_tests(build_nonio_tests)
    if (${build_nonio_tests} AND (NOT "${CONAN_TEST_TARGET}" STREQUAL "coverage"))
        set(${ret} true)
    endif()
endmacro()

macro(can_build_spdk_io_tests ret)
    set(${ret} false)
    if (("${CONAN_TEST_TARGET}" STREQUAL "full") OR ("${CONAN_TEST_TARGET}" STREQUAL "spdk_mode"))
        set(${ret} true)
    endif()
endmacro()

macro(can_build_epoll_io_tests ret)
    set(${ret} false)
    if (("${CONAN_TEST_TARGET}" STREQUAL "full") OR ("${CONAN_TEST_TARGET}" STREQUAL "epoll_mode") OR 
        ("${CONAN_TEST_TARGET}" STREQUAL "coverage"))
        set(${ret} true)
    endif()
endmacro()