name: Homestore Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-22.04"]
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc"]
        prerelease: ["True", "False"]
        tooling: ["Sanitize", "Coverage", "None"]
        exclude:
          - build-type: Debug
            prerelease: "False"
          - build-type: Debug
            tooling: None
          - build-type: Debug
            malloc-impl: tcmalloc
          - build-type: Release
            malloc-impl: libc
          - build-type: Release
            tooling: Sanitize
          - build-type: Release
            tooling: Coverage
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: ${{ matrix.platform }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
      tooling: ${{ matrix.tooling }}
  ChainBuild:
    runs-on: "ubuntu-22.04"
    steps:
    - name: Start HomeReplication Build
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.CHAIN_BUILD_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/eBay/homereplication/actions/workflows/conan_build.yml/dispatches \
          -d '{"ref":"main","inputs":{}}'
      if: ${{ github.ref == 'refs/heads/master' }}
