name: Homestore 3.x Build

on:
  workflow_dispatch:
  push:
    branches:
      - stable/v3.x

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-22.04"]
        build-type: ["Debug", "Release"]
        malloc-impl: ["libc", "tcmalloc"]
        prerelease: ["True", "False"]
        exclude:
          - build-type: Debug
            malloc-impl: tcmalloc
          - malloc-impl: libc
            build-type: Release
            platform: ubuntu-22.04
    uses: ./.github/workflows/build_commit.yml
    with:
      platform: ${{ matrix.platform }}
      build-type: ${{ matrix.build-type }}
      malloc-impl: ${{ matrix.malloc-impl }}
      prerelease: ${{ matrix.prerelease }}
